name: build

env:
  # Common versions
  GO_VERSION: "1.23"
  TZ: Asia/Shanghai

permissions:
  contents: read

on:
  push:
    branches:
      - "*"
    paths:
      - "**.go"
      - "go.mod"
      - ".github/**"

jobs:
  build:
    name: "Build"
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: install task
        run: |
          echo "install task"
          go install github.com/go-task/task/v3/cmd/task@latest
      - name: Build
        run: |
          task ghcr
